name: 🐳 Test docker image
on:
  push:
    branches-ignore:
    - "main"
  pull_request:
    branches-ignore:
    - "main"

jobs:
  test:
    name: 🐳 Test docker image
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm/v7]
    steps:
    - name: 🔧 Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: 🏗️ Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 🐳 Build with tag test | ${{ matrix.platform }}
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile
        push: false
        tags: ${{ github.repository }}:test
        platforms: ${{ matrix.platform }}

# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v4
      
#     - name: Set up QEMUф
#       uses: docker/setup-qemu-action@v3
      
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v3
      
#     - name: Re-login to Docker Hub
#       if: always()  # Выполняется даже при ошибках предыдущих шагов
#       uses: docker/login-action@v3
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
        
#     - name: Build and push multi-arch
#       uses: docker/build-push-action@v5
#       with:
#         context: .
#         platforms: linux/amd64,linux/arm64,linux/arm/v7
#         push: ${{ github.event_name != 'pull_request' }}
#         tags: |
#           kroshka4aplin/wolnut:latest
#           kroshka4aplin/wolnut:${{ github.sha }}
